import { Language, Difficulty } from './types';

export interface BankWord {
  answer: string;
  clue: string;
}

// Answers are A–Z only (no umlauts/ß) so typing and matching work the same
// on every keyboard layout. Clues may use full German orthography.

const EN_EASY: BankWord[] = [
  { answer: 'DAY',   clue: 'Opposite of night' },
  { answer: 'CAT',   clue: 'Pet that meows' },
  { answer: 'DOG',   clue: 'Pet that barks' },
  { answer: 'SUN',   clue: 'Star at the center of our solar system' },
  { answer: 'MOON',  clue: 'It orbits the Earth' },
  { answer: 'BLUE',  clue: 'Color of a clear sky' },
  { answer: 'COLD',  clue: 'Opposite of hot' },
  { answer: 'BALL',  clue: 'Round object used in many sports' },
  { answer: 'TREE',  clue: 'Tall plant with a trunk and branches' },
  { answer: 'FISH',  clue: 'Animal that lives in water' },
  { answer: 'BOOK',  clue: 'You read it' },
  { answer: 'MILK',  clue: 'White drink from cows' },
  { answer: 'RAIN',  clue: 'Water falling from clouds' },
  { answer: 'SNOW',  clue: 'Cold white winter flakes' },
  { answer: 'STAR',  clue: 'It twinkles in the night sky' },
  { answer: 'HOUSE', clue: 'Building people live in' },
  { answer: 'APPLE', clue: 'Red or green fruit' },
  { answer: 'BREAD', clue: 'Baked food made from flour' },
  { answer: 'WATER', clue: 'You drink it — H2O' },
  { answer: 'GREEN', clue: 'Color of grass' },
  { answer: 'HAPPY', clue: 'Feeling of joy' },
  { answer: 'CHAIR', clue: 'You sit on it' },
  { answer: 'TABLE', clue: 'Furniture you eat at' },
  { answer: 'MOUSE', clue: 'Small rodent' },
  { answer: 'HORSE', clue: 'Animal you can ride' },
  { answer: 'CLOUD', clue: 'White fluffy thing in the sky' },
  { answer: 'EGG',   clue: 'A hen lays it' },
  { answer: 'ICE',   clue: 'Frozen water' },
  { answer: 'BED',   clue: 'You sleep in it' },
  { answer: 'RED',   clue: 'Color of a ripe tomato' },
  { answer: 'CAR',   clue: 'Vehicle with four wheels' },
  { answer: 'KEY',   clue: 'It opens a lock' },
  { answer: 'PEN',   clue: 'You write with it' },
  { answer: 'HAT',   clue: 'You wear it on your head' },
  { answer: 'SHOE',  clue: 'You wear it on your foot' },
  { answer: 'DOOR',  clue: 'You open it to enter a room' },
  { answer: 'LION',  clue: 'Big cat called king of the jungle' },
  { answer: 'BIRD',  clue: 'Animal with feathers and wings' },
  { answer: 'CAKE',  clue: 'Sweet baked birthday treat' },
  { answer: 'NOSE',  clue: 'You smell with it' },
  { answer: 'HAND',  clue: 'It has five fingers' },
  { answer: 'FOOT',  clue: 'Body part you stand on' },
  { answer: 'LAMP',  clue: 'It gives light in a room' },
  { answer: 'SALT',  clue: 'White seasoning on every table' },
  { answer: 'TRAIN', clue: 'It runs on rails' },
  { answer: 'NIGHT', clue: 'Opposite of day' },
  { answer: 'BEACH', clue: 'Sandy place by the sea' },
];

const EN_HARD: BankWord[] = [
  { answer: 'PARIS',   clue: 'Capital of France' },
  { answer: 'PACIFIC', clue: 'Largest ocean on Earth' },
  { answer: 'COMPASS', clue: 'Tool whose needle points north' },
  { answer: 'ESSAY',   clue: 'Short written composition' },
  { answer: 'GALAXY',  clue: 'Vast system of stars, like the Milky Way' },
  { answer: 'OXYGEN',  clue: 'Gas we breathe, symbol O' },
  { answer: 'VOLCANO', clue: 'Mountain that can erupt' },
  { answer: 'ECLIPSE', clue: 'When one celestial body blocks another' },
  { answer: 'PYRAMID', clue: 'Ancient Egyptian monument' },
  { answer: 'GRAVITY', clue: 'Force that pulls objects toward Earth' },
  { answer: 'NEUTRON', clue: 'Subatomic particle with no charge' },
  { answer: 'ENZYME',  clue: 'Protein that speeds up reactions' },
  { answer: 'QUARTZ',  clue: 'Common crystalline mineral' },
  { answer: 'SPHINX',  clue: 'Egyptian statue with a lion body' },
  { answer: 'NEBULA',  clue: 'Interstellar cloud of dust and gas' },
  { answer: 'ISOTOPE', clue: 'Atom variant with a different neutron count' },
  { answer: 'THEOREM', clue: 'Proven mathematical statement' },
  { answer: 'LAGOON',  clue: 'Shallow water separated from the sea' },
  { answer: 'GLACIER', clue: 'Slow-moving river of ice' },
  { answer: 'HORIZON', clue: 'Line where sky meets earth' },
  { answer: 'CIPHER',  clue: 'Secret code' },
  { answer: 'MIRAGE',  clue: 'Optical illusion in the desert' },
  { answer: 'TUNDRA',  clue: 'Cold treeless arctic plain' },
  { answer: 'SONNET',  clue: 'Fourteen-line poem' },
  { answer: 'AMBER',   clue: 'Fossilized tree resin' },
  { answer: 'COBALT',  clue: 'Metal used for deep blue pigment' },
  { answer: 'TALON',   clue: 'Claw of a bird of prey' },
  { answer: 'BAZAAR',  clue: 'Middle Eastern market' },
  { answer: 'LARYNX',  clue: 'The voice box' },
  { answer: 'OASIS',   clue: 'Fertile spot in a desert' },
  { answer: 'PLASMA',  clue: 'Fourth state of matter' },
  { answer: 'VERTEX',  clue: 'Corner point of a polygon' },
  { answer: 'ANTHEM',  clue: 'A national song' },
  { answer: 'ORACLE',  clue: 'Ancient source of prophecy' },
  { answer: 'JIGSAW',  clue: 'Puzzle of interlocking pieces' },
  { answer: 'CANYON',  clue: 'Deep gorge carved by a river' },
  { answer: 'METEOR',  clue: 'A shooting star' },
  { answer: 'ZENITH',  clue: 'Point in the sky directly overhead' },
  { answer: 'ARCHIVE', clue: 'Collection of historical records' },
  { answer: 'ECHO',    clue: 'Sound reflected back to its source' },
  { answer: 'PRISM',   clue: 'Glass shape that splits light into colors' },
  { answer: 'ATLAS',   clue: 'Book of maps' },
];

const DE_EASY: BankWord[] = [
  { answer: 'TAG',    clue: 'Gegenteil von Nacht' },
  { answer: 'HUND',   clue: 'Tier, das bellt' },
  { answer: 'KATZE',  clue: 'Haustier, das miaut' },
  { answer: 'SONNE',  clue: 'Sie scheint am Tag' },
  { answer: 'MOND',   clue: 'Er leuchtet in der Nacht' },
  { answer: 'BLAU',   clue: 'Farbe des Himmels' },
  { answer: 'KALT',   clue: 'Gegenteil von warm' },
  { answer: 'BALL',   clue: 'Rundes Spielzeug' },
  { answer: 'BAUM',   clue: 'Pflanze mit Stamm und Ästen' },
  { answer: 'FISCH',  clue: 'Tier, das im Wasser lebt' },
  { answer: 'BUCH',   clue: 'Man liest es' },
  { answer: 'MILCH',  clue: 'Weißes Getränk von der Kuh' },
  { answer: 'REGEN',  clue: 'Wasser, das vom Himmel fällt' },
  { answer: 'SCHNEE', clue: 'Weiße kalte Flocken im Winter' },
  { answer: 'STERN',  clue: 'Er funkelt am Nachthimmel' },
  { answer: 'HAUS',   clue: 'Gebäude zum Wohnen' },
  { answer: 'APFEL',  clue: 'Rotes oder grünes Obst' },
  { answer: 'BROT',   clue: 'Gebackenes Grundnahrungsmittel' },
  { answer: 'WASSER', clue: 'Man trinkt es — H2O' },
  { answer: 'GRAS',   clue: 'Es ist grün und wächst auf der Wiese' },
  { answer: 'ROT',    clue: 'Farbe einer reifen Tomate' },
  { answer: 'AUTO',   clue: 'Fahrzeug mit vier Rädern' },
  { answer: 'TISCH',  clue: 'Möbelstück zum Essen' },
  { answer: 'STUHL',  clue: 'Man sitzt darauf' },
  { answer: 'MAUS',   clue: 'Kleines Nagetier' },
  { answer: 'PFERD',  clue: 'Tier zum Reiten' },
  { answer: 'WOLKE',  clue: 'Weißes Gebilde am Himmel' },
  { answer: 'EIS',    clue: 'Gefrorenes Wasser' },
  { answer: 'BETT',   clue: 'Man schläft darin' },
  { answer: 'HAND',   clue: 'Sie hat fünf Finger' },
  { answer: 'NASE',   clue: 'Damit riecht man' },
  { answer: 'SCHUH',  clue: 'Man trägt ihn am Fuß' },
  { answer: 'HUT',    clue: 'Man trägt ihn auf dem Kopf' },
  { answer: 'LAMPE',  clue: 'Sie spendet Licht im Zimmer' },
  { answer: 'BLUME',  clue: 'Sie blüht im Garten' },
  { answer: 'BIENE',  clue: 'Insekt, das Honig macht' },
  { answer: 'VOGEL',  clue: 'Tier mit Federn und Flügeln' },
  { answer: 'SALZ',   clue: 'Weißes Gewürz auf jedem Tisch' },
  { answer: 'ZUG',    clue: 'Er fährt auf Schienen' },
  { answer: 'BERG',   clue: 'Hohe Erhebung in der Landschaft' },
  { answer: 'SEE',    clue: 'Stehendes Gewässer' },
  { answer: 'WALD',   clue: 'Viele Bäume zusammen' },
  { answer: 'NACHT',  clue: 'Gegenteil von Tag' },
  { answer: 'BRIEF',  clue: 'Man schickt ihn mit der Post' },
  { answer: 'SCHIFF', clue: 'Es fährt auf dem Meer' },
  { answer: 'KAESE',  clue: 'Milchprodukt mit Löchern (ä = AE)' },
];

const DE_HARD: BankWord[] = [
  { answer: 'BERLIN',     clue: 'Hauptstadt von Deutschland' },
  { answer: 'FICHTE',     clue: 'Nadelbaum' },
  { answer: 'AUFSATZ',    clue: 'Schriftliche Abhandlung in der Schule' },
  { answer: 'ZIRKEL',     clue: 'Werkzeug zum Zeichnen von Kreisen' },
  { answer: 'RUBIN',      clue: 'Kostbarer roter Edelstein' },
  { answer: 'VULKAN',     clue: 'Berg, der ausbrechen kann' },
  { answer: 'GLETSCHER',  clue: 'Langsam fließender Eisstrom' },
  { answer: 'HORIZONT',   clue: 'Linie, an der sich Himmel und Erde treffen' },
  { answer: 'SAUERSTOFF', clue: 'Gas zum Atmen, Symbol O' },
  { answer: 'PYRAMIDE',   clue: 'Altägyptisches Bauwerk' },
  { answer: 'GALAXIE',    clue: 'Sternsystem wie die Milchstraße' },
  { answer: 'KOMPASS',    clue: 'Gerät, dessen Nadel nach Norden zeigt' },
  { answer: 'LAGUNE',     clue: 'Flaches Gewässer, vom Meer getrennt' },
  { answer: 'STEPPE',     clue: 'Baumlose Graslandschaft' },
  { answer: 'QUARZ',      clue: 'Häufiges kristallines Mineral' },
  { answer: 'MAGNET',     clue: 'Er zieht Eisen an' },
  { answer: 'PLANET',     clue: 'Himmelskörper, der einen Stern umkreist' },
  { answer: 'KOMET',      clue: 'Schweifstern' },
  { answer: 'ANKER',      clue: 'Er hält das Schiff an seinem Platz' },
  { answer: 'ORAKEL',     clue: 'Antike Weissagungsstätte' },
  { answer: 'THEATER',    clue: 'Haus für Schauspiel' },
  { answer: 'BIBLIOTHEK', clue: 'Haus voller Bücher' },
  { answer: 'INSEL',      clue: 'Land, umgeben von Wasser' },
  { answer: 'KANAL',      clue: 'Künstliche Wasserstraße' },
  { answer: 'TIGER',      clue: 'Gestreifte Großkatze' },
  { answer: 'ADLER',      clue: 'Großer Greifvogel' },
  { answer: 'EICHE',      clue: 'Laubbaum mit Eicheln' },
  { answer: 'AMBOSS',     clue: 'Werkzeug des Schmieds' },
  { answer: 'SILBER',     clue: 'Edelmetall, Symbol Ag' },
  { answer: 'KUPFER',     clue: 'Rötliches Metall, Symbol Cu' },
  { answer: 'MARMOR',     clue: 'Edler Stein für Statuen' },
  { answer: 'OPER',       clue: 'Musiktheater mit Gesang' },
  { answer: 'ATLAS',      clue: 'Buch voller Landkarten' },
  { answer: 'ZEBRA',      clue: 'Gestreiftes Steppentier' },
  { answer: 'DELFIN',     clue: 'Kluges Meeressäugetier' },
  { answer: 'RAKETE',     clue: 'Sie fliegt ins Weltall' },
  { answer: 'SPIEGEL',    clue: 'Man sieht sich darin' },
  { answer: 'SCHATTEN',   clue: 'Dunkler Bereich ohne Licht' },
  { answer: 'NEBEL',      clue: 'Tiefe Wolke am Boden' },
  { answer: 'EBBE',       clue: 'Niedrigwasser an der Küste' },
  { answer: 'WINTER',     clue: 'Kälteste Jahreszeit' },
  { answer: 'ORCHESTER',  clue: 'Großes Ensemble von Musikern' },
];

export function getWordBank(language: Language, difficulty: Difficulty): BankWord[] {
  if (language === 'en') return difficulty === 'easy' ? EN_EASY : EN_HARD;
  return difficulty === 'easy' ? DE_EASY : DE_HARD;
}
